/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedWorkspaceRouteImport } from './routes/_authed/workspace'
import { Route as AuthedUserRouteImport } from './routes/_authed/user'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedBoardsRouteImport } from './routes/_authed/boards'
import { Route as AuthedActivityRouteImport } from './routes/_authed/activity'
import { Route as AuthedCardsNumberRouteImport } from './routes/_authed/cards.$number'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkspaceRoute = AuthedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserRoute = AuthedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBoardsRoute = AuthedBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCardsNumberRoute = AuthedCardsNumberRouteImport.update({
  id: '/cards/$number',
  path: '/cards/$number',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRoute
  '/activity': typeof AuthedActivityRoute
  '/boards': typeof AuthedBoardsRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/user': typeof AuthedUserRoute
  '/workspace': typeof AuthedWorkspaceRoute
  '/cards/$number': typeof AuthedCardsNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof PostsRoute
  '/activity': typeof AuthedActivityRoute
  '/boards': typeof AuthedBoardsRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/user': typeof AuthedUserRoute
  '/workspace': typeof AuthedWorkspaceRoute
  '/cards/$number': typeof AuthedCardsNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/posts': typeof PostsRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/boards': typeof AuthedBoardsRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/user': typeof AuthedUserRoute
  '/_authed/workspace': typeof AuthedWorkspaceRoute
  '/_authed/cards/$number': typeof AuthedCardsNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/activity'
    | '/boards'
    | '/notifications'
    | '/user'
    | '/workspace'
    | '/cards/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts'
    | '/activity'
    | '/boards'
    | '/notifications'
    | '/user'
    | '/workspace'
    | '/cards/$number'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/posts'
    | '/_authed/activity'
    | '/_authed/boards'
    | '/_authed/notifications'
    | '/_authed/user'
    | '/_authed/workspace'
    | '/_authed/cards/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PostsRoute: typeof PostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workspace': {
      id: '/_authed/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthedWorkspaceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/user': {
      id: '/_authed/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthedUserRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/boards': {
      id: '/_authed/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof AuthedBoardsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cards/$number': {
      id: '/_authed/cards/$number'
      path: '/cards/$number'
      fullPath: '/cards/$number'
      preLoaderRoute: typeof AuthedCardsNumberRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedBoardsRoute: typeof AuthedBoardsRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedUserRoute: typeof AuthedUserRoute
  AuthedWorkspaceRoute: typeof AuthedWorkspaceRoute
  AuthedCardsNumberRoute: typeof AuthedCardsNumberRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedBoardsRoute: AuthedBoardsRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedUserRoute: AuthedUserRoute,
  AuthedWorkspaceRoute: AuthedWorkspaceRoute,
  AuthedCardsNumberRoute: AuthedCardsNumberRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PostsRoute: PostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
